FROM node:20-alpine

WORKDIR /app

# Copiar solo los archivos necesarios para el mock server
COPY package*.json ./
COPY mock-server ./mock-server

# Instalar dependencias
RUN npm install json-server

# Exponer el puerto 3000
EXPOSE 3000

# Comando para iniciar el mock server
CMD ["npx", "json-server", "--watch", "mock-server/db.json", "--host", "0.0.0.0", "--port", "3000", "--delay", "500"]